version: '3.4'
services:
  postgis:
    image: docker.io/postgres
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=colabdac
    ports:
      - '5432:5432'
    volumes:
      - ./database_postgres/data:/var/lib/postgresql/data
      - ./database_postgres/scripts/create.sql:/docker-entrypoint-initdb.d/init.sql